name: Android CI
  
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build debug apk with Gradle
      run: cd project && bash ./gradlew clean assemble
    - uses: actions/upload-artifact@v2
      with:
        name: app-debug.apk
        path: project/app/build/outputs/apk/debug/app-debug.apk
